Cast TokenValue.__str__ return value to string
jurismarches/luqum pull request #74
Opened 2022-07-12 16:55 UTC by delkopiso

fixes #69

2022-07-13 09:51 UTC, alexgarel approved these changes
Really cool change.

I approve so you can merge as is, but if you find the time to add a test that would be super-cool :-)

2022-07-13 09:53 UTC, alexgarel requested changes
Sorry my first approval was a bit too quick. Can you consider my suggestion ?

2022-07-13 09:53 UTC, alexgarel commented on luqum/head_tail.py
> +        return str(self.value)
Hum sorry I think this would be better:

```suggestion
        return str(self.value) if self.value else ""
```

2022-07-13 16:30 UTC, delkopiso commented
@alexgarel that makes sense, I've applied your suggestion.

2022-07-15 13:13 UTC, alexgarel approved these changes
Perfect, thank you so much :-)

2022-07-15 13:14 UTC, merged